import { NextRequest, NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'

// Local development only: sign in with a magic-link token hash generated by
// scripts/assistant-seed.mjs, so the assistant can be driven in a browser
// without a password. Returns 404 in production.
export async function GET(req: NextRequest) {
  if (process.env.NODE_ENV === 'production' || process.env.VERCEL) return new NextResponse('Not found', { status: 404 })
  const tokenHash = req.nextUrl.searchParams.get('token_hash')
  if (!tokenHash) return new NextResponse('token_hash required', { status: 400 })
  const supabase = await createClient()
  const { error } = await supabase.auth.verifyOtp({ type: 'magiclink', token_hash: tokenHash })
  if (error) return new NextResponse(`Login failed: ${error.message}`, { status: 400 })
  return NextResponse.redirect(new URL('/assistant', req.url))
}
